apiVersion: v1
kind: ConfigMap

metadata:
  name: gateway-config

data:
  ReverseProxy__Clusters__trip-service__Destinations__default__Address: http://trip-clusterip
  ReverseProxy__Clusters__payment-service__Destinations__default__Address: http://payment-clusterip
  ReverseProxy__Clusters__provider-service__Destinations__default__Address: http://provider-clusterip
  ReverseProxy__Clusters__notification-service__Destinations__default__Address: http://notification-clusterip