apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity
    app.kubernetes.io/part-of: myres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: keycloak-storage
  resources:
    requests:
      storage: 2Gi