apiVersion: v1
kind: Service

metadata:
  name: keycloak-clusterip

  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity
    app.kubernetes.io/part-of: myres

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity

  ports:
    - name: http
      port: 80
      targetPort: 8080