apiVersion: v1
kind: Service
metadata:
  name: mssql-nodeport
  labels:
    purpose: local-debug
    app.kubernetes.io/name: mssql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: myres
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: mssql
    app.kubernetes.io/component: database
  ports:
    - name: tds
      protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 31434