apiVersion: v1
kind: Service
metadata:
  name: notification-clusterip
  labels:
    app.kubernetes.io/name: notification
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: myres  
spec:
  type: ClusterIP
  #sessionAffinity: ClientIP
  selector:
    app.kubernetes.io/name: notification
    app.kubernetes.io/component: api
  ports:
  - name: http
    port: 80
    targetPort: 8080