apiVersion: v1
kind: Service
metadata:
  name: trip-clusterip
  labels:
    app.kubernetes.io/name: trip
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: myres  
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: trip
    app.kubernetes.io/component: api
  ports:
  - name: http
    port: 80
    targetPort: 8080