apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-svc
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: myres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: myres
    spec:
      containers:
        - name: myres-frontend-svc
          ports:
            - name: http
              containerPort: 80
