apiVersion: v1
kind: Service
metadata:
  name: frontend-clusterip
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: myres
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: 80
